version: '4.39.0'
services:
  dev-db:
    image: postgres:17
    ports: 
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
    - net
networks:
  net:

